<298..298> in i5433.scala
class Fail cannot be instantiated due to a conflict between its parents when
resolving a super-call:

1. One of its parent (trait C) contains a call super.foo in its body.
2. Because B comes before C in the linearization
   order of Fail, and because B overrides foo,
   this is resolved as a call to super[B].foo in Fail.
3. However:
   X (the type of super[B].foo in Fail)
   is not a subtype of
   Y (the type of super[C].foo in Fail)

Here are two possible ways to resolve this:

1. Change the linearization order of Fail such that
   C comes before B.
2. Alternatively, replace super.foo in the body of trait C by a
   super-call to a specific parent, e.g. super[A].foo
